# -*- coding: utf-8 -*-
"""colab_controles.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E-DouNTagyINsOt6Y4H8AeB16T2mzpQA

# Exercício 10.8 (Cap. 10 – Nise) — Diagrama de Nyquist

**Sistema com realimentação unitária:**

$$
G(s) = \dfrac{K(s + 5)}{(s^2 + 6s + 100)(s^2 + 4s + 25)}
$$

## O programa:

- **a)** traça o diagrama de Nyquist de $G(s)$;
- **b)** encontra e mostra o valor e a frequência do cruzamento do diagrama com o eixo real ($\text{Im}[G(j\omega)] = 0$).

> Convertido de MATLAB para Python usando as bibliotecas **numpy**, **scipy** e **matplotlib**.
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy import signal
from scipy.optimize import brentq


def montar_planta(K=1):
    """Monta a funcao de transferencia G(s) em forma polinomial."""
    # numerador: K(s + 5)
    num = np.array([K, 5 * K])

    # denominador: (s^2 + 6s + 100)(s^2 + 4s + 25)
    den1 = np.array([1, 6, 100])
    den2 = np.array([1, 4, 25])
    den = np.convolve(den1, den2)

    return signal.TransferFunction(num, den)


def resposta_em_frequencia(sistema, w):
    """Calcula G(jw) para um vetor de frequencias w (rad/s)."""
    w_out, resp = signal.freqresp(sistema, w=w)
    return resp


def encontrar_cruzamento_eixo_real(sistema, w_min=1e-3, w_max=1e3, n=200000):
    """
    Encontra a(s) frequencia(s) em que Im[G(jw)] = 0 (w > 0),
    isto e, o(s) ponto(s) em que o diagrama de Nyquist cruza
    o eixo real.
    """
    w = np.linspace(w_min, w_max, n)
    resp = resposta_em_frequencia(sistema, w)
    im = resp.imag

    cruzamentos = []
    # procura mudancas de sinal em Im[G(jw)]
    sinais = np.sign(im)
    trocas = np.where(np.diff(sinais) != 0)[0]

    for idx in trocas:
        w_a, w_b = w[idx], w[idx + 1]

        def im_func(wf):
            return resposta_em_frequencia(sistema, np.array([wf])).imag[0]

        try:
            w_zero = brentq(im_func, w_a, w_b)
            re_zero = resposta_em_frequencia(sistema, np.array([w_zero])).real[0]
            cruzamentos.append((w_zero, re_zero))
        except ValueError:
            continue

    return cruzamentos


def plotar_nyquist(sistema, w_min=1e-3, w_max=1e3, n=20000, cruzamentos=None):
    """
    Traca o diagrama de Nyquist em duas visoes lado a lado:

      - Painel esquerdo: visao geral, incluindo o ponto critico -1+j0,
        para avaliar a distancia da curva ate a instabilidade;
      - Painel direito: zoom na regiao da curva (que costuma ser muito
        pequena quando K e pequeno), para ver a forma do laco e o(s)
        ponto(s) de cruzamento com o eixo real com clareza.
    """
    w = np.linspace(w_min, w_max, n)
    resp = resposta_em_frequencia(sistema, w)

    fig, (ax_geral, ax_zoom) = plt.subplots(1, 2, figsize=(13, 6.5))

    for ax, titulo in [(ax_geral, "Visao geral"), (ax_zoom, "Zoom na curva")]:
        ax.plot(resp.real, resp.imag, "b", label="w > 0")
        ax.plot(resp.real, -resp.imag, "b--", label="w < 0")
        ax.plot(-1, 0, "rx", markersize=10, markeredgewidth=2, label="-1 + j0")

        if cruzamentos:
            for w_c, re_c in cruzamentos:
                ax.plot(re_c, 0, "ko", markersize=6, zorder=5)

        ax.axhline(0, color="gray", linewidth=0.7)
        ax.axvline(0, color="gray", linewidth=0.7)
        ax.set_xlabel("Eixo Real")
        ax.set_ylabel("Eixo Imaginario")
        ax.set_title(titulo)
        ax.grid(True)

    # painel geral: escala fixa para incluir o -1 e dar nocao de distancia
    margem_geral = max(0.3, 1.3 * np.max(np.abs(resp)))
    ax_geral.set_xlim(-1.3, margem_geral)
    ax_geral.set_ylim(-margem_geral, margem_geral)
    ax_geral.set_aspect("equal", adjustable="box")
    ax_geral.legend(loc="upper right", fontsize=8)

    # painel de zoom: escala baseada apenas nos valores da propria curva
    folga = 0.15
    re_min, re_max = resp.real.min(), resp.real.max()
    im_min, im_max = min(resp.imag.min(), -resp.imag.max()), max(resp.imag.max(), -resp.imag.min())
    dre = (re_max - re_min) or 1e-6
    dim = (im_max - im_min) or 1e-6
    ax_zoom.set_xlim(re_min - folga * dre, re_max + folga * dre)
    ax_zoom.set_ylim(im_min - folga * dim, im_max + folga * dim)

    if cruzamentos:
        for w_c, re_c in cruzamentos:
            ax_zoom.annotate(
                f"w = {w_c:.3f} rad/s\nRe = {re_c:.5f}",
                xy=(re_c, 0),
                xytext=(0.55, 0.12),
                textcoords="axes fraction",
                fontsize=9,
                arrowprops=dict(arrowstyle="->", color="black", lw=1),
            )

    fig.suptitle(
        "Diagrama de Nyquist - G(s) = K(s+5) / [(s^2+6s+100)(s^2+4s+25)]",
        fontsize=12,
    )

    plt.tight_layout(rect=[0, 0, 1, 0.95])
    plt.show()

K = 1  # ganho do sistema (pode ser alterado)

G = montar_planta(K)

cruzamentos = encontrar_cruzamento_eixo_real(G)

print("=" * 55)
print(f"Sistema: G(s) com K = {K}")
print("Cruzamento(s) do diagrama de Nyquist com o eixo real:")
for w_c, re_c in cruzamentos:
    print(f"  Frequencia: w = {w_c:.4f} rad/s")
    print(f"  Valor no eixo real: Re[G(jw)] = {re_c:.6f}")
print("=" * 55)

plotar_nyquist(G, cruzamentos=cruzamentos)